"use strict";

const fs = require("fs");
const path = require("path");

function fail(message, err) {
  const detail = err && err.message ? ` (${err.message})` : "";
  console.error(`[inject-env] ${message}${detail}`);
  process.exit(1);
}

function parseBool(raw, fallback) {
  if (raw === undefined || raw === null || String(raw).trim() === "") {
    return fallback;
  }
  const v = String(raw).trim().toLowerCase();
  if (["1", "true", "yes", "on"].includes(v)) return true;
  if (["0", "false", "no", "off"].includes(v)) return false;
  fail(`Invalid boolean for PORTFOLIO_DEV_TOOLS: ${raw}`);
}

function loadDotEnv(filePath) {
  if (!fs.existsSync(filePath)) return {};
  let text;
  try {
    text = fs.readFileSync(filePath, "utf8");
  } catch (err) {
    fail(`Could not read ${filePath}`, err);
  }
  const out = {};
  for (const line of text.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq < 1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

function main() {
  const root = path.resolve(process.argv[2] || path.join(__dirname, ".."));
  const envFile = path.join(root, ".env");
  const fromFile = loadDotEnv(envFile);
  const enabled = parseBool(
    process.env.PORTFOLIO_DEV_TOOLS !== undefined
      ? process.env.PORTFOLIO_DEV_TOOLS
      : fromFile.PORTFOLIO_DEV_TOOLS,
    true
  );

  const target = path.join(root, "js", "env.js");
  const body =
    `/* Generated by scripts/inject-env.js - do not edit by hand in dist. */\n` +
    `window.__PORTFOLIO_ENV__ = {\n` +
    `  DEV_TOOLS: ${enabled ? "true" : "false"}\n` +
    `};\n`;

  try {
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, body);
  } catch (err) {
    fail(`Could not write ${target}`, err);
  }
  console.log(
    `[inject-env] Wrote ${target} with DEV_TOOLS=${enabled}`
  );
}

main();
